
SYSTEM = :gba

TILESET_WIDTH_IN_TILES = 16
TILESET_HEIGHT_IN_TILES = 32
LENGTH_OF_TILESET_IN_BLOCKS = TILESET_WIDTH_IN_TILES*TILESET_HEIGHT_IN_TILES - 1 # -1 because the first tile in a tileset is always blank.
NUM_BLOCKS_IN_TILESET_IMAGE = TILESET_WIDTH_IN_TILES*TILESET_HEIGHT_IN_TILES
TILE_WIDTH = 32
TILE_HEIGHT = 32
SCREEN_WIDTH_IN_TILES = 8
SCREEN_HEIGHT_IN_TILES = 8
SCREEN_WIDTH_IN_PIXELS = SCREEN_WIDTH_IN_TILES*TILE_WIDTH
SCREEN_HEIGHT_IN_PIXELS = SCREEN_HEIGHT_IN_TILES*TILE_HEIGHT
SIZE_OF_A_SCREEN_IN_BYTES = 2*SCREEN_WIDTH_IN_TILES*SCREEN_HEIGHT_IN_TILES
