
SYSTEM = :nds

TILESET_WIDTH_IN_TILES = 16
TILESET_HEIGHT_IN_TILES = 64
LENGTH_OF_TILESET_IN_BLOCKS = TILESET_WIDTH_IN_TILES*TILESET_HEIGHT_IN_TILES - 1 # -1 because the first tile in a tileset is always blank.
NUM_BLOCKS_IN_TILESET_IMAGE = TILESET_WIDTH_IN_TILES*TILESET_HEIGHT_IN_TILES
TILE_WIDTH = 16
TILE_HEIGHT = 16
SCREEN_WIDTH_IN_TILES = 16
SCREEN_HEIGHT_IN_TILES = 12
SCREEN_WIDTH_IN_PIXELS = SCREEN_WIDTH_IN_TILES*TILE_WIDTH
SCREEN_HEIGHT_IN_PIXELS = SCREEN_HEIGHT_IN_TILES*TILE_HEIGHT
SIZE_OF_A_SCREEN_IN_BYTES = 2*SCREEN_WIDTH_IN_TILES*SCREEN_HEIGHT_IN_TILES

HARDCODED_BOSSRUSH_ROOM_IDS = nil
